In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json
# this will be disabled for privacy purpose
from config import g_keys

ImportError: cannot import name 'g_keys' from 'config' (/Users/russ/opt/anaconda3/envs/bootcamp/lib/python3.7/site-packages/config/__init__.py)

In [2]:
# read in the weather dataframe 
# used relative path
vacation_df = pd.read_csv('../weatherPy/weather_df')
vacation_df.head()

# creating dataframe with humidity and cities
locations1 = vacation_df[['Latitude', 'Longitude']]
locations1

# make sure humidity data is float
humidity_data = vacation_df['Humidity'].astype(float)
humidity_max = humidity_data.max()
humidity_max

100.0

In [3]:
# plot humidity heat maps
fig = gmaps.figure()

heat_maps1=gmaps.heatmap_layer(locations1, 
                               weights=humidity_data, 
                               max_intensity=humidity_max, 
                               point_radius=2, 
                               dissipating=False)

fig.add_layer(heat_maps1)

fig

Figure(layout=FigureLayout(height='420px'))

In [4]:
# narrow dataframe according to requirements
# req.1 temp 70>x<80
# req.2 windspeed <10mph
# req.3 cloudiness = 0

temp_df=vacation_df[(vacation_df['Temperatures']>70)&(vacation_df['Temperatures']<80)]
#temp_df.head()
windspeed_df=temp_df[temp_df['Windspeed']<10]
#windspeed_df
final_df=windspeed_df[windspeed_df['Cloudiness']==0]
final_df.reset_index()
#print(len(final_df))
#final_df

,index,City,Country,Latitude,Longitude,Humidity,Windspeed,Cloudiness,Temperatures,Date
0,32,belyy yar,RU,53.6039,91.3903,56,4.47,0,75.85,1655376325
1,40,rundu,NaN,-17.9333,19.7667,20,7.83,0,76.12,1655376326
2,123,sikeston,US,36.8767,-89.5879,83,5.75,0,76.87,1655376348
3,152,chipiona,ES,36.7366,-6.4370,78,8.05,0,75.42,1655376355
4,222,nigde,TR,37.8333,34.7500,35,5.75,0,72.46,1655376371
5,230,boulder city,US,35.9786,-114.8325,17,0.00,0,75.16,1655376374
6,257,lexington,US,37.9887,-84.4777,81,4.61,0,77.32,1655376380
7,321,bodmin,GB,50.4715,-4.7243,49,4.61,0,70.50,1655376399
8,351,lumberton,US,34.6182,-79.0086,88,0.00,0,71.56,1655376406
9,353,clearwater,US,27.9659,-82.8001,83,5.01,0,78.33,1655376133
10,394,kuito,AO,-12.3833,16.9333,65,8.05,0,77.14,1655376416
11,437,mutoko,ZW,-17.3970,32.2268,22,4.36,0,77.76,1655376426
12,505,sonoita,MX,31.8500,-112.8333,29,4.45,0,78.75,1655376444
13,523,tarpon springs,US,28.1461,-82.7568,82,0.00,0,77.92,1655376448

In [6]:
# generate lists of items required
hotel_name=[]
hotel_address=[]
hotel_latitude=[]
hotel_longitude=[]
hotel_rating=[]

print('---------------\nHotel information\n---------------')
# iterate through each row
for index, row in final_df.iterrows():
    city = row['City']
    coordinates=f"{row['Latitude']},{row['Longitude']}"
    keyword='lodging'
    
    # set params
    params={
        'location':coordinates,
        'type':'hotel',
        'keyword':keyword,
        'radius':5000,
        'key':g_keys
    }
    
    base_url='https://maps.googleapis.com/maps/api/place/nearbysearch/json'
    response=requests.get(base_url,params=params).json()
    # Check the url to indentify appropriate keys and value to parse in
    # print(json.dumps(response, indent=4, sort_keys=True))
    try:
        hotel_name.append(response['results'][0]['name'])
        hotel_address.append(response['results'][0]['vicinity'])
        hotel_latitude.append(response['results'][0]['geometry']['location']['lat'])
        hotel_longitude.append(response['results'][0]['geometry']['location']['lng'])
        hotel_rating.append(response['results'][0]['rating'])
        print(f'processing info for {index} in {city}')
        # add to the df
        final_df.loc[index, 'Hotel Name']=response['results'][0]['name']
    except:
        print(f'no information for this lodging. Skipping...')
print('------------------\nEND')

---------------
Hotel information
---------------
processing info for 32 in belyy yar

/Users/russ/opt/anaconda3/envs/bootcamp/lib/python3.7/site-packages/pandas/core/indexing.py:1684: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = infer_fill_value(value)
/Users/russ/opt/anaconda3/envs/bootcamp/lib/python3.7/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

processing info for 40 in rundu
processing info for 123 in sikeston
processing info for 152 in chipiona
no information for this lodging. Skipping...
processing info for 230 in boulder city
processing info for 257 in lexington
processing info for 321 in bodmin
processing info for 351 in lumberton
processing info for 353 in clearwater
processing info for 394 in kuito
processing info for 437 in mutoko
processing info for 505 in sonoita
processing info for 523 in tarpon springs
------------------
END

In [7]:
final_df.dropna()
final_df

,City,Country,Latitude,Longitude,Humidity,Windspeed,Cloudiness,Temperatures,Date,Hotel Name
32,belyy yar,RU,53.6039,91.3903,56,4.47,0,75.85,1655376325,Pasportnyy Stol
40,rundu,NaN,-17.9333,19.7667,20,7.83,0,76.12,1655376326,The Four Valleys Guesthouse
123,sikeston,US,36.8767,-89.5879,83,5.75,0,76.87,1655376348,Comfort Inn & Suites Sikeston I-55
152,chipiona,ES,36.7366,-6.4370,78,8.05,0,75.42,1655376355,Chipionabeachhouse
222,nigde,TR,37.8333,34.7500,35,5.75,0,72.46,1655376371,NaN
230,boulder city,US,35.9786,-114.8325,17,0.00,0,75.16,1655376374,Quality Inn
257,lexington,US,37.9887,-84.4777,81,4.61,0,77.32,1655376380,Guest Line Inc
321,bodmin,GB,50.4715,-4.7243,49,4.61,0,70.50,1655376399,The Shooting Lodge
351,lumberton,US,34.6182,-79.0086,88,0.00,0,71.56,1655376406,Hotel Lunberton
353,clearwater,US,27.9659,-82.8001,83,5.01,0,78.33,1655376133,The Palms Hideaway
394,kuito,AO,-12.3833,16.9333,65,8.05,0,77.14,1655376416,Pensão Executiva
437,mutoko,ZW,-17.3970,32.2268,22,4.36,0,77.76,1655376426,Nyamakwere Lodges
505,sonoita,MX,31.8500,-112.8333,29,4.45,0,78.75,1655376444,Hotel Excelsior
523,tarpon springs,US,28.1461,-82.7568,82,0.00,0,77.92,1655376448,The Oxford House

In [9]:
# plot layered maps using hotel coordinates
# get locations first
locations=final_df[['Latitude','Longitude']]

# create info box 
info_box_build="""
<d1>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
</d1>
"""
info_box=[info_box_build.format(**row)for index, row in final_df.iterrows()]

# add a layer to heat maps
marker_layer=gmaps.marker_layer(locations, info_box_content=info_box)
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))